import './js/mobile-menu'
import './js/explore-choco'
import './js/feedback'
import './js/modal2'
import './js/play'
import './js/review'
import './js/reviews-swiper'
import './js/submit'
import './js/swiper'
import './js/swiper-products'
import './js/modal'

